/** GSRTC Journey Demo design: an independent traveller preview with blue rule lines, compact records, and action-led controls. */
import { Bell, BusFront, ChevronRight, CircleUserRound, Clock3, Download, MapPin, TicketCheck, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { BookingShell } from "@/components/BookingShell";

const nav = ["Overview", "My journeys", "Saved passengers", "Wallet", "Support"];
const routePulseLogo = "/manus-storage/routepulse-logo_c9f17078.png";

export default function Dashboard() {
  const [, navigate] = useLocation();
  return <BookingShell step="ticket" eyebrow="Traveller dashboard" title="Your GSRTC Journey Demo desk"><div className="dashboard-layout"><aside className="dashboard-sidebar"><div className="traveller-card"><CircleUserRound /><span><b>Traveller profile</b><small>guest@demo.example</small></span></div><nav>{nav.map((item, index) => <button key={item} className={index === 0 ? "is-active" : ""} onClick={() => index > 0 && toast.info(`${item} opens in the connected traveller service.`)}>{item}<ChevronRight /></button>)}</nav></aside><section className="dashboard-content"><div className="dashboard-summary-grid"><div><span><TicketCheck />Sample journeys</span><strong>1</strong><small>Demo itinerary</small></div><div><span><Clock3 />Journey history</span><strong>4</strong><small>Illustrative records</small></div><div><span><WalletCards />Wallet balance</span><strong>₹0</strong><small>Demo account</small></div></div><section className="upcoming-journey"><div className="dashboard-seal"><img src={routePulseLogo} alt="" /><span>Independent demo record</span></div><div className="upcoming-heading"><div><span>Sample journey</span><h2>Ahmedabad <i /> Vadodara</h2><p>Sun, 23 Aug 2026 · GSRTC Demo Express · GJ-D420</p></div><span className="journey-confirmation">Ticket preview</span></div><div className="upcoming-details"><span><b>Boarding</b>Central Bus Terminal, Bay 12 · 06:30</span><span><b>Seat</b>A3 · Volvo AC Seater</span><button onClick={() => navigate("/tracking")}><MapPin />Track demo service</button><button onClick={() => navigate("/ticket?seats=A3&name=Traveller")}><Download />Ticket preview</button></div></section><section className="journey-history"><div className="history-heading"><h2>Sample journey records</h2><button onClick={() => toast.info("Complete journey history is available after sign-in.")}>View all <ChevronRight /></button></div><div className="history-table"><div className="history-row history-labels"><span>Journey</span><span>Date</span><span>Seat</span><span>Status</span></div>{[{ route: "Surat → Ahmedabad", date: "11 Jun 2026", seat: "C2", status: "Completed" }, { route: "Vadodara → Anand", date: "23 Apr 2026", seat: "B1", status: "Completed" }, { route: "Ahmedabad → Rajkot", date: "14 Feb 2026", seat: "D4", status: "Cancelled" }].map((item) => <div className="history-row" key={item.route}><span><BusFront />{item.route}</span><span>{item.date}</span><span>{item.seat}</span><span className={item.status === "Cancelled" ? "cancelled" : "completed"}>{item.status}</span></div>)}</div></section><div className="dashboard-alert"><Bell /><span><b>Demo notifications</b><small>Operator alerts become available only when an authorised account and data provider are connected.</small></span><button onClick={() => toast.info("Alerts will be configurable after sign-in.")}>Manage</button></div></section></div></BookingShell>;
}
