/** GSRTC Journey Demo design: civic ledger-framed payment preview with sample UPI app choices and no real transaction. */
import { useState } from "react";
import { ArrowRight, Building2, BusFront, CreditCard, Landmark, ShieldCheck, Smartphone, TicketCheck, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import { BookingShell, JourneyMiniCard } from "@/components/BookingShell";

const methods = [{ id: "upi", label: "UPI apps", icon: Smartphone }, { id: "card", label: "Credit / Debit Card", icon: CreditCard }, { id: "bank", label: "Net Banking", icon: Landmark }, { id: "wallet", label: "Demo Wallet", icon: WalletCards }];
const upiApps = [{ id: "gpay", label: "Google Pay", monogram: "G" }, { id: "phonepe", label: "PhonePe", monogram: "P" }, { id: "bhim", label: "BHIM", monogram: "B" }];

export default function Payment() {
  const [, navigate] = useLocation();
  const [method, setMethod] = useState("upi");
  const [selectedUpiApp, setSelectedUpiApp] = useState("gpay");
  const params = new URLSearchParams(window.location.search);
  const seats = params.get("seats") || "A3";
  const total = seats.split(",").filter(Boolean).length * 489 + 24;
  const base = window.location.search.replace(/^\?/, "");
  const currentApp = upiApps.find((app) => app.id === selectedUpiApp) ?? upiApps[0];
  const ctaLabel = method === "upi" ? `Generate ${currentApp.label} preview` : "Generate booking preview";
  return <BookingShell step="payment" eyebrow="Payment preview" title="Choose a demo payment method"><div className="payment-layout"><section className="payment-panel"><div className="payment-ledger"><div className="payment-ledger-head"><TicketCheck /><span><b>Sample payment ledger</b><small>GJ-DEMO-82467 · Independent civic prototype</small></span><em>Preview only</em></div><div className="payment-ledger-route"><span><b>Ahmedabad</b><small>06:30 · Boarding</small></span><i><BusFront /></i><span><b>Vadodara</b><small>12:20 · Arrival</small></span><strong>GJ-D420</strong></div></div><div className="sandbox-banner"><ShieldCheck /><div><b>Independent demo mode</b><p>This GSRTC-inspired prototype is not affiliated with GSRTC. It does not collect money, open a UPI app, or create a real ticket.</p></div></div><div className="payment-methods"><h2>Sample payment method</h2>{methods.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setMethod(id)} className={method === id ? "payment-method is-selected" : "payment-method"}><Icon /><span>{label}</span><i /></button>)}</div>{method === "upi" && <section className="upi-app-selector"><div className="upi-app-heading"><div><h2>Choose a UPI app</h2><p>Use this to preview how a UPI choice could appear inside the transit service desk before a real payment system is connected.</p></div><span>Preview only</span></div><div className="upi-app-grid">{upiApps.map((app) => <button key={app.id} type="button" onClick={() => setSelectedUpiApp(app.id)} className={selectedUpiApp === app.id ? `upi-app-card is-selected ${app.id}` : `upi-app-card ${app.id}`}><i>{app.monogram}</i><span>{app.label}</span><small>UPI preview</small></button>)}</div><div className="upi-preview-note"><ShieldCheck /><span><b>{currentApp.label} selected for preview</b><small>No UPI intent, account, or payment will be opened from this demo.</small></span></div></section>}<div className="payment-input-preview"><label>{method === "upi" ? "Selected UPI app" : method === "card" ? "Card details" : method === "bank" ? "Choose bank" : "Wallet number"}<input disabled value={method === "upi" ? `${currentApp.label} · passenger payment preview` : method === "card" ? "4111 1111 1111 1111" : method === "bank" ? "Demo national bank" : "DEMO-100-002"} /></label><small>Example-only field; no payment credential is requested or stored.</small></div></section><aside className="payment-summary-card"><JourneyMiniCard seats={seats} /><div className="payment-total"><span>Demo amount</span><strong>₹{total}</strong></div><button onClick={() => navigate(`/ticket?${base}&mode=sandbox&paymentMethod=${encodeURIComponent(method)}&upiApp=${encodeURIComponent(selectedUpiApp)}`)} className="primary-booking-button">{ctaLabel} <ArrowRight /></button><p><Building2 />No funds will be debited in demo mode.</p></aside></div></BookingShell>;
}
